export const Topics = {
  0: "All",
  2: "Business",
  4: "Business--Accounting",
  6: "Business--Logistics",
  8: "Business--Marketing",
  10: "Business--Marketing: Advertising",
  12: "Business--Management",
  14: "Business--Management: Project Management",
  16: "Business--MLM",
  18: "Business--Responsibility and Business Ethics",
  20: "Business--Trading",
  22: "Business--E-Commerce",
  24: "Biology",
  26: "Biology--Estestvoznananie",
  28: "Biology--Anthropology",
  30: "Biology--Anthropology: Evolution",
  32: "Biology--Biostatistics",
  34: "Biology--Biotechnology",
  36: "Biology--Biophysics",
  38: "Biology--Biochemistry",
  40: "Biology--Biochemistry: enologist",
  42: "Biology--Virology",
  44: "Biology--Genetics",
  46: "Biology--Zoology",
  48: "Biology--Zoology: Paleontology",
  50: "Biology--Zoology: Fish",
  52: "Biology--Microbiology",
  54: "Biology--Molecular",
  56: "Biology--Molecular: Bioinformatics",
  58: "Biology--Plants: Botany",
  60: "Biology--Plants: Agriculture and Forestry",
  62: "Biology--Ecology",
  64: "Geography",
  66: "Geography--Geodesy. Cartography",
  68: "Geography--Local History",
  70: "Geography--Local history: Tourism",
  72: "Geography--Meteorology, Climatology",
  74: "Geography--Russia",
  76: "Geology",
  78: "Geology--Hydrogeology",
  80: "Geology--Mining",
  82: "Housekeeping, leisure",
  84: "Housekeeping, leisure--Aquaria",
  86: "Housekeeping, leisure--Astrology",
  88: "Housekeeping, leisure--Pet",
  90: "Housekeeping, leisure--Games: Board Games",
  92: "Housekeeping, leisure--Games: Chess",
  94: "Housekeeping, leisure--Collecting",
  96: "Housekeeping, leisure--Beauty, image",
  98: "Housekeeping, leisure--Cooking",
  100: "Housekeeping, leisure--Fashion, Jewelry",
  102: "Housekeeping, leisure--Hunting and Game Management",
  104: "Housekeeping, leisure--Benefits Homebrew",
  106: "Housekeeping, leisure--Professions and Trades",
  108: "Housekeeping, leisure--Handicraft",
  110: "Housekeeping, leisure--Handicraft: Cutting and Sewing",
  112: "Housekeeping, leisure--Garden, garden",
  114: "Art",
  116: "Art--Design: Architecture",
  118: "Art--Graphic Arts",
  120: "Art--Cinema",
  122: "Art--Music",
  124: "Art--Music: Guitar",
  126: "Art--Photo",
  128: "History",
  130: "History--American Studies",
  132: "History--Archaeology",
  134: "History--Military History",
  136: "History--Memoirs, Biographies",
  138: "Computers",
  140: "Computers--Web-design",
  142: "Computers--Algorithms and Data Structures",
  144: "Computers--Algorithms and Data Structures: Cryptography",
  146: "Computers--Algorithms and Data Structures: Image Processing",
  148: "Computers--Algorithms and Data Structures: Pattern Recognition",
  150: "Computers--Algorithms and Data Structures: Digital watermarks",
  152: "Computers--Databases",
  154: "Computers--Security",
  156: "Computers--Information Systems",
  158: "Computers--Information Systems: EC businesses",
  160: "Computers--Cybernetics",
  162: "Computers--Cybernetics: Artificial Intelligence",
  164: "Computers--Cryptography",
  166: "Computers--Lectures, monographs",
  168: "Computers--Media",
  170: "Computers--Operating Systems",
  172: "Computers--Organization and Data Processing",
  174: "Computers--Programming",
  176: "Computers--Programming: Libraries API",
  178: "Computers--Programming: Games",
  180: "Computers--Programming: Compilers",
  182: "Computers--Programming: Modeling languages",
  184: "Computers--Programming: Programming Languages",
  186: "Computers--Programs: TeX, LaTeX",
  188: "Computers--Software: Office software",
  190: "Computers--Software: Adobe Products",
  192: "Computers--Software: Macromedia Products",
  194: "Computers--Software: CAD",
  196: "Computers--Software: Systems: scientific computing",
  198: "Computers--Networking",
  200: "Computers--Networking: Internet",
  202: "Computers--System Administration",
  204: "Literature",
  206: "Literature--Fiction",
  208: "Literature--Library",
  210: "Literature--Detective",
  212: "Literature--Children",
  214: "Literature--Comics",
  216: "Literature--Literary",
  218: "Literature--Poetry",
  220: "Literature--Prose",
  222: "Literature--Folklore",
  224: "Literature--Fantasy",
  226: "Mathematics",
  228: "Mathematics--Algebra",
  230: "Mathematics--Algebra: Linear Algebra",
  232: "Mathematics--Algorithms and Data Structures",
  234: "Mathematics--Analysis",
  236: "Mathematics--Wavelets and signal processing",
  238: "Mathematics--Probability",
  240: "Mathematics--Computational Mathematics",
  242: "Mathematics--Geometry and Topology",
  244: "Mathematics--Puzzle",
  246: "Mathematics--Dynamical Systems",
  248: "Mathematics--Discrete Mathematics",
  250: "Mathematics--Differential Equations",
  252: "Mathematics--Combinatorics",
  254: "Mathematics--The complex variable",
  256: "Mathematics--Computer Algebra",
  258: "Mathematics--Lectures",
  260: "Mathematics--Logic",
  262: "Mathematics--Mathematicsematical Statistics",
  264: "Mathematics--Mathematicsematical Physics",
  266: "Mathematics--Continued fractions",
  268: "Mathematics--Fuzzy Logic and Applications",
  270: "Mathematics--Optimal control",
  272: "Mathematics--Optimization. Operations Research",
  274: "Mathematics--Applied Mathematicsematics",
  276: "Mathematics--Symmetry and group",
  278: "Mathematics--Automatic Control Theory",
  280: "Mathematics--Graph Theory",
  282: "Mathematics--Game Theory",
  284: "Mathematics--Operator Theory",
  286: "Mathematics--Number Theory",
  288: "Mathematics--Functional Analysis",
  290: "Mathematics--Numerical Analysis",
  292: "Mathematics--Elementary",
  294: "Medicine",
  296: "Medicine--Anatomy and physiology",
  298: "Medicine--Anesthesiology and Intensive Care",
  300: "Medicine--Diseases",
  302: "Medicine--Diseases: Internal Medicine",
  304: "Medicine--Histology",
  306: "Medicine--Homeopathy",
  308: "Medicine--Dermatology",
  310: "Medicine--Diabetes",
  312: "Medicine--immunology",
  314: "Medicine--Infectious diseases",
  316: "Medicine--Yoga",
  318: "Medicine--Cardiology",
  320: "Medicine--Chinese Medicine",
  322: "Medicine--Clinical Medicine",
  324: "Medicine--Molecular Medicine",
  326: "Medicine--Natural Medicine",
  328: "Medicine--Popular scientific literature",
  330: "Medicine--Neurology",
  332: "Medicine--Oncology",
  334: "Medicine--ENT",
  336: "Medicine--Ophthalmology",
  338: "Medicine--Pediatrics",
  340: "Medicine--Dentistry, Orthodontics",
  342: "Medicine--Trial",
  344: "Medicine--Therapy",
  346: "Medicine--Pharmacology",
  348: "Medicine--Feng Shui",
  350: "Medicine--Surgery, Orthopedics",
  352: "Medicine--Endocrinology",
  354: "Medicine--Epidemiology",
  356: "Science (General)",
  358: "Science (general)--International Conferences and Symposiums",
  360: "Science (general)--Science of Science",
  362: "Science (general)--Scientific-popular",
  364: "Science (general)--Scientific and popular: Journalism",
  366: "Education",
  368: "Education--Theses abstracts",
  370: "Education--International Conferences and Symposiums",
  372: "Education--self-help books",
  374: "Education--Elementary",
  376: "Education--Encyclopedia",
  378: "Other Social Sciences",
  380: "Other Social Sciences--Journalism, Media",
  382: "Other Social Sciences--Cultural",
  384: "Other Social Sciences--Politics",
  386: "Other Social Sciences--Politics: International Relations",
  388: "Other Social Sciences--Sociology",
  390: "Other Social Sciences--Philosophy",
  392: "Other Social Sciences--Philosophy: Critical Thinking",
  394: "Other Social Sciences--Ethnography",
  396: "Psychology",
  398: "Psychology--Hypnosis",
  400: "Psychology--The art of communication",
  402: "Psychology--Love, erotic",
  404: "Psychology--Neuro-Linguistic Programming",
  406: "Psychology--Pedagogy",
  408: "Psychology--Creative Thinking",
  410: "Religion",
  412: "Religion--Buddhism",
  414: "Religion--kabbalah",
  416: "Religion--Orthodoxy",
  418: "Religion--Esoteric, Mystery",
  420: "Technique",
  422: "Technique--Automation",
  424: "Technique--Aerospace Equipment",
  426: "Technique--Water Treatment",
  428: "Technique--Military equipment",
  430: "Technique--Military equipment: Weapon",
  432: "Technique--Publishing",
  434: "Technology--Space Science",
  436: "Technique--Light Industry",
  438: "Technique--Materials",
  440: "Technology--Mechanical Engineering",
  442: "Technique--Metallurgy",
  444: "Technique--Metrology",
  446: "Technique--Safety and Security",
  448: "Technique--Nanotechnology",
  450: "Technique--Oil and Gas Technologies",
  452: "Technique--Oil and Gas Technologies: Pipelines",
  454: "Technique--Regulatory Literature",
  456: "Technique--Patent Business. Ingenuity. Innovation",
  458: "Technique--Food Manufacturing",
  460: "Technique--Instrument",
  462: "Technique--Industry: Metallurgy",
  464: "Technique--industrial equipment and technology",
  466: "Technique--Missiles",
  468: "Technique--Communication",
  470: "Technique--Communication: Telecommunications",
  472: "Technique--Construction",
  476: "Technique--Construction: Ventilation and Air Conditioning",
  478: "Technique--Construction: Renovation and interior design",
  480: "Technique--Construction: Renovation and interior design: Saunas",
  482: "Technique--Construction: Cement Industry",
  484: "Technique--Heat",
  486: "Technique--Fuel Technology",
  488: "Technique--Transport",
  490: "Technique--Transportation: Aviation",
  492: "Technique--Transportation: Cars, motorcycles",
  494: "Technique--Transportation: Rail",
  496: "Technique--Transportation: Ships",
  498: "Technique--Refrigeration",
  500: "Technique--Electronics",
  502: "Technique--Electronics: Hardware",
  504: "Technique--Electronics: Fiber Optics",
  506: "Technique--Electronics: Home Electronics",
  508: "Technique--Electronics: Microprocessor Technology",
  510: "Technique--Electronics: Signal Processing",
  512: "Technique--Electronics: Radio",
  514: "Technique--Electronics: Robotics",
  516: "Technique--Electronics: VLSI",
  518: "Technique--Electronics: TV. Video",
  520: "Technique--Electronics: Telecommunications",
  522: "Technique--Electronics: Electronics",
  524: "Technique--Energy",
  526: "Technique--Energy: Renewable Energy",
  528: "Physics",
  530: "Physics--Astronomy",
  532: "Physics--Astronomy: Astrophysics",
  534: "Physics--Geophysics",
  536: "Physics--Quantum Mechanics",
  538: "Physics--Quantum Physics",
  540: "Physics--Crystal Physics",
  542: "Physics--Mechanics",
  544: "Physics--Mechanics: Oscillations and Waves",
  546: "Physics--Mechanics: Mechanics of deformable bodies",
  548: "Physics--Mechanics: Fluid Mechanics",
  550: "Physics--Mechanics: Nonlinear dynamics and chaos",
  552: "Physics--Mechanics: Strength of Materials",
  554: "Physics--Mechanics: Theory of Elasticity",
  556: "Physics--General courses",
  558: "Physics--Optics",
  560: "Physics--Spectroscopy",
  562: "Physics--Theory of Relativity and Gravitation",
  564: "Physics--Thermodynamics and Statistical Mechanics",
  566: "Physics--Physics of the Atmosphere",
  568: "Physics--Physics of lasers",
  570: "Physics--Plasma Physics",
  572: "Physics--Solid State Physics",
  574: "Physics--Electricity and Magnetism",
  576: "Physics--Electrodynamics",
  578: "Physical Education and Sport",
  580: "Physical education and sport--Bodybuilding",
  582: "Physical education and sport--Martial Arts",
  584: "Physical education and sport--Bike",
  586: "Physical education and sport--Survival",
  588: "Physical Education and Sport--Sport fishing",
  590: "Physical education and sport--Fencing",
  592: "Chemistry",
  594: "Chemistry--Analytical Chemistry",
  596: "Chemistry--Materials",
  598: "Chemistry--Inorganic Chemistry",
  600: "Chemistry--Organic Chemistry",
  602: "Chemistry--Pyrotechnics and explosives",
  604: "Chemistry--Pharmacology",
  606: "Chemistry--Physical Chemistry",
  608: "Chemistry--Chemical",
  610: "Economy",
  612: "Economy--Investing",
  614: "Economy--Mathematical Economics",
  616: "Economy--Popular",
  618: "Economy--Markets",
  620: "Economy--Econometrics",
  622: "Jurisprudence--Criminology, Forensic Science",
  624: "Jurisprudence--Criminology: Court. examination",
  626: "Jurisprudence--Law",
  628: "Linguistics",
  630: "Linguistics--Foreign",
  632: "Linguistics--Foreign: English",
  634: "Linguistics--Foreign: French",
  636: "Linguistics--Comparative Studies",
  638: "Linguistics--Linguistics",
  640: "Linguistics--Rhetoric",
  642: "Linguistics--Russian Language",
  644: "Linguistics--Dictionaries",
  646: "Linguistics--Stylistics",
};
